### ISSUE TITLE
'lower' and 'is_on' attribute 

### ISSUE THREAD

**Issue by m2k2** [MisterWil/abodepy#19]
AttributeError: 'NoneType' object has no attribute 'lower'
AttributeError: 'AbodeDevice' object has no attribute 'is_on'

I think these may be related to Nest items integrating with abode.

**Comment by m2k2** [comment]
@MisterWil what's the best way to contact you privately? I'd be willing to send you some of the devices and jsons I have for those devices.

**Comment by MisterWil** [comment]
Thanks! You can email devices to wilrader@gmail.com

**Comment by MisterWil** [comment]
Pretty sure this issue was fixed in the 0.11.8 abodepy release. Unknown devices are no longer created (no AbodeDevice objects are ever created). I also added a check that the version tag exists before comparing it against the 'minipir' string.

Made a PR against HA that was merged and should be in 0.54.
