### ISSUE TITLE
First Alert ZWave Smoke/CO Detectors not recognized

### ISSUE THREAD

**Issue by FreeWillyB** [MisterWil/abodepy#62]
There is no class created in the devices folder or CONST values for smoke detectors. I got something hacked together last night that got at minimum will recognize the device to test it but doesn’t create the any of the methods or attributes for the class. If it’s ok with you I’ll put together a more proper solution and submit it to you so we can get those devices working in apps like home assistant.

**Comment by shred86** [comment]
The reason is the Smoke/CO2 sensor JSON data doesn’t directly report anything besides it being “Online” or “Offline”, similar to others like the glass break sensors (unless this recently changed). Abode’s socketio server does push messages for alarmed events which both Abodepy and Home Assistant already support.

**Comment by FreeWillyB** [comment]
I had some more time just now to look, and I suppose you're talking about the "statuses" key in the JSON. Looks like you are correct, and the value is still being passed through as an empty list. What a shame they don't pass that through. It seems as if the only alternative then would be to get ZWAVE stick or something for my home assistant. It would have been so convenient to just use the built-in radio inside the gateway!
